language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
services:
- memcached
- redis
before_script: phpenv config-add myconfig.ini
script: run.sh
env:
  global:
    secure: ggI89+W2j/zCt1v+7ngi8VCRcRcHSRK4tRHLcBxX0m5aMP5sKirvgTB28oVY0ozSh0bwPtzL7FF62MJ7fnElOEfTpR7nEapEExeke/9uRekud5QdZyRNClja2YLLYXaqDxTQBCJ8oeuDjK7W6n50mXh1Rb11FcxK5TXZzcGGatk=
